export const DISPLAY_ALERT = 'SHOW_ALERT';

export const CLEAR_ALERT = 'CLEAR_ALERT';

//InitialState
export const INITIAL_STATE = 'INITIAL_STATE';

// Register
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

//RESEND VERIFICATION TOKEN LINK
export const RESEND_LINK_BEGIN = 'RESEND_LINK_BEGIN';
export const RESEND_LINK_SUCCESS = 'RESEND_LINK_SUCCESS';
export const RESEND_LINK_ERROR = 'RESEND_LINK_ERROR';

//MEAIL VERIFICATION
export const EMAIL_VERIFICATION_BEGIN = 'EMAIL_VERIFICATION_BEGIN';
export const EMAIL_VERIFICATION_SUCCESS = 'EMAIL_VERIFICATION_SUCCESS';
export const EMAIL_VERIFICATION_ERROR = 'EMAIL_VERIFICATION_ERROR';

// Login
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
